CREATE TABLE PAIS (
    id_pais NUMBER(38) NOT NULL,
    nome VARCHAR2(50) NOT NULL,    
    PRIMARY KEY(id_pais)
);

CREATE TABLE ESTADO (
	id_estado NUMBER(38) NOT NULL,
	id_pais NUMBER(38) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	PRIMARY KEY(id_estado)
);

ALTER TABLE ESTADO
ADD CONSTRAINT FK_ID_PAIS FOREIGN KEY ( id_pais ) REFERENCES PAIS( id_pais );

CREATE TABLE CIDADE	 (
	id_cidade NUMBER(38) NOT NULL,
	id_estado NUMBER(38) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	PRIMARY KEY(id_cidade)
);

ALTER TABLE CIDADE
ADD CONSTRAINT FK_ID_ESTADO FOREIGN KEY ( id_estado ) REFERENCES ESTADO( id_estado );

CREATE TABLE BAIRRO	 (
	id_bairro NUMBER(38) NOT NULL,
	id_cidade NUMBER(38) NOT NULL,
	id_estado NUMBER(38) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	PRIMARY KEY(id_bairro)
);

ALTER TABLE BAIRRO
	ADD CONSTRAINT FK_BAIRRO_ID_ESTADO FOREIGN KEY ( id_estado ) REFERENCES ESTADO( id_estado );

ALTER TABLE BAIRRO
	ADD CONSTRAINT FK_ID_CIDADE FOREIGN KEY ( id_cidade ) REFERENCES CIDADE( id_cidade );

CREATE TABLE ENDERECO	 (
	id_endereco NUMBER(38) NOT NULL,
	id_bairro NUMBER(38) NOT NULL,
	id_cidade NUMBER(38) NOT NULL,	
	logradouro VARCHAR(255) NOT NULL,
	numero NUMBER(38) NOT NULL,
	complemento VARCHAR(100),
	cep CHAR(9),
	PRIMARY KEY(id_ENDERECO)
);

ALTER TABLE ENDERECO
	ADD CONSTRAINT FK_ID_BAIRRO FOREIGN KEY ( id_bairro ) REFERENCES BAIRRO( id_bairro );

ALTER TABLE ENDERECO
	ADD CONSTRAINT FK_ENDERECO_ID_CIDADE FOREIGN KEY ( id_cidade ) REFERENCES CIDADE( id_cidade );

CREATE SEQUENCE seq_pais
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE seq_estado
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE seq_cidade
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE seq_bairro
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;

CREATE SEQUENCE seq_endereco
	START WITH 1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;


-- ADD PAIS
INSERT INTO PAIS p 
(p.ID_PAIS, p.NOME)
VALUES 
(seq_pais.nextval,'Brasil');

INSERT INTO PAIS p 
(p.ID_PAIS, p.NOME)
VALUES 
(seq_pais.nextval,'Argentina');
-- ADD PAIS

-- ADD ESTADO
INSERT INTO ESTADO es 
(es.ID_ESTADO, es.ID_PAIS, es.NOME)
VALUES 
(seq_estado.nextval, 1, 'RS');

INSERT INTO ESTADO es 
(es.ID_ESTADO, es.ID_PAIS, es.NOME)
VALUES 
(seq_estado.nextval, 1, 'PR');

INSERT INTO ESTADO es 
(es.ID_ESTADO, es.ID_PAIS, es.NOME)
VALUES 
(seq_estado.nextval, 2, 'JJ');

INSERT INTO ESTADO es 
(es.ID_ESTADO, es.ID_PAIS, es.NOME)
VALUES 
(seq_estado.nextval, 2, 'AA');
-- ADD ESTADO

-- ADD CIDADE
INSERT INTO CIDADE ci 
(ci.ID_CIDADE, ci.ID_ESTADO, ci.NOME)
VALUES 
(seq_cidade.nextval, 1, 'Porto Alegre');

INSERT INTO CIDADE ci 
(ci.ID_CIDADE, ci.ID_ESTADO, ci.NOME)
VALUES 
(seq_cidade.nextval, 2, 'Curitiba');

INSERT INTO CIDADE ci 
(ci.ID_CIDADE, ci.ID_ESTADO, ci.NOME)
VALUES 
(seq_cidade.nextval, 3, 'Buenos Aires');

INSERT INTO CIDADE ci 
(ci.ID_CIDADE, ci.ID_ESTADO, ci.NOME)
VALUES 
(seq_cidade.nextval, 4, 'Mendoza');
-- ADD CIDADE

-- ADD BAIRRO
INSERT INTO BAIRRO ba 
(ba.ID_BAIRRO, ba.ID_CIDADE, ba.ID_ESTADO, ba.NOME)
VALUES 
(seq_bairro.nextval, 1, 1, 'Ruben Berta');

INSERT INTO BAIRRO ba 
(ba.ID_BAIRRO, ba.ID_CIDADE, ba.ID_ESTADO, ba.NOME)
VALUES 
(seq_bairro.nextval, 2, 2, 'Boa Vista');

INSERT INTO BAIRRO ba 
(ba.ID_BAIRRO, ba.ID_CIDADE, ba.ID_ESTADO, ba.NOME)
VALUES 
(seq_bairro.nextval, 3, 3, 'Bairro de BA');

INSERT INTO BAIRRO ba 
(ba.ID_BAIRRO, ba.ID_CIDADE, ba.ID_ESTADO, ba.NOME)
VALUES 
(seq_bairro.nextval, 4, 4, 'Bairro de MEN');
-- ADD BAIRRO

-- ADD ENDERECO
INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 1, 1, 'Rua Maria', 885, 'Apto 200', '123456789');

INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 1, 1, 'Rua José', 772, 'Apto 100', '987654321');

INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 2, 2, 'Rua Jão', 1500, 'Apto 111', '125856789');

INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 2, 2, 'Rua Gerundia', 2000, 'Apto 151', '989985321');

INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 3, 3, 'Rua Tadeu', 222, 'Apto 225', '154356789');

INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 3, 3, 'Rua Olokinhomeu', 2526, 'Apto 171', '922185321');

INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 4, 4, 'Rua dos Maias', 580, 'Apto 425', '155556789');

INSERT INTO ENDERECO en 
(en.ID_ENDERECO, en.ID_BAIRRO, en.ID_CIDADE, en.LOGRADOURO, en.NUMERO, en.COMPLEMENTO, en.CEP)
VALUES 
(seq_endereco.nextval, 4, 4, 'Rua dos Incas', 226, 'Apto 371', '922125821');
-- ADD ENDERECO

SELECT * FROM PAIS ORDER BY NOME;

SELECT LOGRADOURO, CEP FROM ENDERECO WHERE UPPER(LOGRADOURO) LIKE 'A%';

SELECT * FROM ENDERECO WHERE CEP LIKE '%0';

SELECT * FROM ENDERECO WHERE NUMERO BETWEEN 1 AND 100;

SELECT * FROM ENDERECO WHERE UPPER(LOGRADOURO) LIKE 'RUA%' ORDER BY CEP DESC;

SELECT COUNT(ID_ENDERECO) FROM ENDERECO;

SELECT COUNT(ID_ENDERECO), ID_CIDADE FROM ENDERECO GROUP BY ID_CIDADE;

	
UPDATE ENDERECO EN 
SET 
	EN.LOGRADOURO = 'Rua jacaré', 
	EN.COMPLEMENTO = '29'
WHERE 
	EN.ID_ENDERECO = 2 OR EN.ID_ENDERECO = 3;
	
UPDATE ENDERECO EN 
SET 
	EN.NUMERO = 999999
WHERE 
	EN.ID_ENDERECO = 4;
	
DELETE 
	FROM ENDERECO EN
WHERE EN.ID_ENDERECO = (select max(ID_ENDERECO) from ENDERECO);

DELETE 
	FROM ENDERECO EN
WHERE EN.NUMERO = 999999;

DELETE 
	FROM ENDERECO;
